### ISSUE TITLE
Firmware does not compile under arduino-cli (3 blockers: nanopb include, non-self-contained headers, duplicate mesh_message); no CI firmware build

### ISSUE THREAD

**Issue by superbrobenji** [superbrobenji/lattice-nodes#49]
## Summary

The firmware **does not compile under `arduino-cli`** (`arduino-cli compile --fqbn esp32:esp32:esp32 main`). The Arduino IDE builds it via different include resolution, which masks three separate issues. No CI job compiles the firmware — only host unit/e2e tests (cmake) and CodeQL build — so this has gone unnoticed.

Surfaced while attempting to re-measure `docs/memory_usage.md` (which itself requires a firmware ELF + `xtensa-esp32-elf-size`); the measurement is currently blocked by all three.

## The three blockers

1. **nanopb include path not configured** — `main/src/mesh/serialization/mesh.pb.h:6` does `#include "pb.h"`, but `main/src/mesh/serialization/nanopb` is not on the default sketch include path.
   ```
   mesh.pb.h:6:10: fatal error: pb.h: No such file or directory
   ```
   Fix: add the nanopb dir to the include path (build property / `library.properties`), or flatten nanopb into the sketch tree.

2. **Non-self-contained headers** — `main/src/app/ButtonHandler.h` (e.g. lines 85, 98) uses `Logger` / `LogLevel` **unqualified**, relying on the `using namespace lattice::utils;` that `main.ino:22` declares *before* the include. Compiled on its own, the names are undeclared:
   ```
   ButtonHandler.h:98:9: error: 'Logger' has not been declared
   ButtonHandler.h:98:63: error: 'LogLevel' has not been declared
   ```
   This is the same class of latent bug the old `docs/memory_usage.md` noted for `Serial_Adapter` — it moved in the #24 restructure, it was not fixed. Fix: each header `#include`s what it uses and fully-qualifies (`lattice::utils::Logger`, `lattice::utils::LogLevel`).

3. **Duplicate `mesh_message` typedef** — the vendored `main/lib/lattice-protocol/c/mesh_message.h` is auto-scanned from the Arduino `lib/` dir; its `typedef struct … mesh_message` collides with the `using ::mesh_message;` aliases (`main/src/mesh/Mesh.h:33`, `Adapter.h:12`, `SerialFraming.h:9`):
   ```
   lattice-protocol/c/mesh_message.h:27:3: error: conflicting declaration 'typedef struct mesh_message mesh_message'
   ```
   Fix: keep the vendored C tree out of the Arduino `lib/` auto-scan, or gate its inclusion.

## Impact

Medium. The firmware still builds and flashes from the Arduino IDE, so shipped devices are unaffected. But:
- The build is **not reproducible** on any non-IDE toolchain (CI, `arduino-cli`, PlatformIO).
- Blocker #2 is a latent **correctness** bug — those headers are only valid because of include ordering in one `.ino`.
- Blocks accurate flash/RAM re-measurement (`docs/memory_usage.md` numbers are stale since the #24 restructure + Phases 1–5).

## Where

- `main/src/mesh/serialization/mesh.pb.h:6`
- `main/src/app/ButtonHandler.h` (unqualified `Logger`/`LogLevel`)
- `main/lib/lattice-protocol/c/mesh_message.h:27` vs `using ::mesh_message` in `Mesh.h`/`Adapter.h`/`SerialFraming.h`
- No firmware-compile job in `.github/workflows/`

## Options

- Fix blockers 1–3 so `arduino-cli compile --fqbn esp32:esp32:esp32 main` succeeds.
- Add a CI firmware-build + `xtensa-esp32-elf-size` size-report job so (a) the build can't silently break outside the IDE again, and (b) `docs/memory_usage.md` can be regenerated automatically.
- As part of #2, sweep other headers for the same unqualified-name / missing-include pattern.

## Severity

Medium. Not user-facing today, but breaks build portability + reproducibility and is a blocker for memory-optimization work.

**Comment by superbrobenji** [comment]
## Discovery update (2026-07-22) — reproduced on real toolchain (arduino-cli 1.5.1 + esp32@3.3.10)

Drove the actual build. Two corrections + one new blocker:

**Blocker #3 root cause is misdescribed here.** It is **not** `lib/` auto-scan — arduino-cli 1.5.1 adds no `-I` for `main/lib/lattice-protocol` (verified via `compile_commands.json`). The real cause: `mesh_message.h` uses `#pragma once`, which fails to dedupe when the header is reached via two different include-path spellings (`main/src/adapter/../../lib/...` via `Adapter.h` vs `main/lib/...` via `ReplayCache.h`/`Mesh.h`). Removing redundant includes is whack-a-mole; the robust fix is a traditional `#ifndef` guard — best emitted **upstream in `cmd/gen-headers`** so it survives regeneration.

**Blockers #1 and #2 confirmed** and fixes verified: (#1) nanopb dir on include path; (#2) fully-qualify `lattice::utils::Logger`/`LogLevel` in `ButtonHandler.h` (9 sites, only file affected).

**NEW blocker #4 (was masked behind the compile errors): link fails.** Once #1–#3 are fixed, compilation succeeds but linking fails on `mbedtls_chachapoly_*` — `MBEDTLS_CHACHAPOLY_C` is disabled in the core's mbedtls. Filed as #54.

**Resolution pivot:** rather than patch arduino-cli, the fix for #54 is to migrate the build to **ESP-IDF (arduino-as-component)** with a custom `mbedtls_config`. Blockers #1–#3 remedies still apply (nanopb include dir → CMake; header qualification is a correctness fix regardless; include guard upstream). This issue's CI goal changes from "arduino-cli compiles" to "ESP-IDF build+link + size report." See umbrella spec `docs/superpowers/specs/2026-07-22-close-all-open-issues-design.md`, Phase 0.
